apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
        - image: SOFE-3980U-Lab3-RodneyStanislaus/binarycalculator
          name: binarycalculator
          ports:
            - containerPort: 3306
              name: binarycalculator
